### ISSUE TITLE
This implementation can deadlock given the current Future contract

### ISSUE THREAD

**Issue by carllerche** [proman21/futures-mutex#1]
If a task calls `poll_lock` and the mutex cannot be acquired, it gets added to the queue. At some point, the task will be notified, however there is no guarantee that once the task is notified that it will call `poll_lock` again. In fact, it may not even be obvious to the user why the task doesn't call `poll_lock`. For example:

```rust
set_timeout().select(resource.lock())
    .and_then(...)
```

In this case, the task could be notified because the lock becomes available, but then when the task tries to run again, the future returned by `set_timeout` completes. In this case, the lock will never be polled again by the task and the mutex will never be unlocked again.

**Comment by proman21** [comment]
Hmm I thought I had covered this case in my implementation. Currently the lock is reacquired through a race. Nearly all the tasks are purged from the queue and notified, so any dead tasks won't deadlock; another living task will pick it up.

I can see issues where `FutMutexGuard` might not be dropped in some of the future operations like `select`, which will deadlock the lock until that future drops.

**Comment by carllerche** [comment]
How is the lock reacquired through a race?

**Comment by carllerche** [comment]
Ah, I see `FutMutexAcquired` releases on drop. That works if the value is dropped, however it is not uncommon for futures to be held around but not polled again in a timely fashion. This behavior would result in starvation.

**Comment by carllerche** [comment]
To be clear, I think that **this** option is the best you can do. However, it should be very clearly documented the starvation case.

**Comment by proman21** [comment]
Yep! I have no solution for this other than to drop my values ASAP or to unlock things as quickly as possible.

**Comment by carllerche** [comment]
Another option is to have a queue of callbacks that get called w/ a `&mut T` reference to the inner... then you can use a oneshot to communicate back w/ the result of the computation made in the closure.

**Comment by carllerche** [comment]
Example:

```rust
let res = my_async_mutex.lock(|val| {
    let cur = *val;
    *val += 1;
    cur
});

res.and_then(|res| println!("GOT: {:?}", res);
```

**Comment by proman21** [comment]
That does work but it does add the closure environment and move semantics that I couldn't use with the code I was building. I was really trying to get Mutex like usage and patterns in a future friendly format. I think that style is suited to completely different concurrency pattern.
