### ISSUE TITLE
The `concurrent` test sometimes deadlock

### ISSUE THREAD

**Issue by tomaka** [proman21/futures-mutex#3]
I've just spent two hours on this problem and still have no idea why, so I thought I'd at least open an issue.
Replacing the `MsQueue<Task>` with a `Mutex<Vec<Task>>` fixes the problem, but is obviously not the greatest solution.

As a hint, the deadlock always happens after either `a` or `b` are finished, never in the middle of the processing.

**Comment by proman21** [comment]
Thank you for reporting this. Currently, I'm going to be deprecating this project as I no longer use it and it has significant bugs like the one you found. If you'd like to continue working on it, I'm more than happy for you to copy the source code and work on it.

**Comment by tomaka** [comment]
We're currently using [a local version of this library for a WIP project](https://github.com/libp2p/rust-libp2p/tree/master/futures-mutex), so we're going to try fix it. We had planned to upstream our changes to your repo at a later point in time.

No offence, but in my opinion it doesn't really make sense to add deprecation notices everywhere. Whether a crate will not receive any change doesn't matter at all for the user who is satisfied with it.
